S02 us30 create category
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-DigiCode pull request #34
Opened 2024-06-12 10:33 UTC by JohaneDecamps

2024-06-12 10:51 UTC, MichaelLELU approved these changes

2024-06-12 12:11 UTC, ioayoub requested changes

2024-06-12 12:11 UTC, ioayoub commented on server/app/controllers/caterogyActions.js
> +    const category = { ...req.body, id: req.params.id};
huh ?

2024-06-12 13:50 UTC, JohaneDecamps commented on server/app/controllers/caterogyActions.js
> +    const category = { ...req.body, id: req.params.id};
done :)

2024-06-12 14:28 UTC, aurelienLavanchy requested changes

2024-06-12 14:28 UTC, aurelienLavanchy commented on server/app/controllers/caterogyActions.js
> +    await tables.category.delete(req.params.id);
For consistency's sake, consider destructuring `id` like previously instead of passing `req.params.id` directly

2024-06-12 14:28 UTC, aurelienLavanchy commented on server/database/models/CategoryRepository.js
> +        [category.name]
Where does `category.name` come from ?
You're passing `category` from `req.body`, there is no "name" inside (?)

2024-06-12 14:28 UTC, aurelienLavanchy commented on server/app/controllers/caterogyActions.js
> +    await tables.category.edit(id, name);
There is no `edit` method in CategoryRepository, but there is `update`

2024-06-12 14:28 UTC, aurelienLavanchy commented on server/database/tables.js
> +const ItemRepository = require("./models/ItemRepository")
We're not using "items", you can remove the ItemRepository import

2024-06-12 15:29 UTC, aurelienLavanchy submitted a review, later dismissed

2024-06-13 08:41 UTC, MichaelLELU submitted a review, later dismissed

2024-06-13 08:52 UTC, aurelienLavanchy submitted a review, later dismissed

2024-06-13 08:56 UTC, MichaelLELU submitted a review, later dismissed

2024-06-13 09:04 UTC, camille-haxa approved these changes

2024-06-13 10:04 UTC, aurelienLavanchy approved these changes

2024-06-13 10:04 UTC, MichaelLELU approved these changes

2024-06-13 10:05 UTC, camille-haxa approved these changes

2024-06-13 10:36 UTC, aurelienLavanchy approved these changes

2024-06-13 10:39 UTC, ioayoub approved these changes

2024-06-13 10:40 UTC, MichaelLELU approved these changes

2024-06-13 10:40 UTC, merged