fix: router delete in categories and videos
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-DigiCode pull request #47
Opened 2024-06-19 16:23 UTC by camille-haxa

fix router on this branch because it's when we realized the error on the server side

2024-06-19 16:25 UTC, MichaelLELU approved these changes

2024-06-19 16:36 UTC, aurelienLavanchy approved these changes

2024-06-20 07:53 UTC, ioayoub requested changes
Handle orphan videos if a category is deleted

2024-06-20 09:04 UTC, MichaelLELU approved these changes

2024-06-20 09:24 UTC, JohaneDecamps approved these changes

2024-06-20 09:26 UTC, merged