S02 us31 create navbar
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-DigiCode pull request #48
Opened 2024-06-19 16:32 UTC by aurelienLavanchy

2024-06-19 17:30 UTC, MichaelLELU submitted a review, later dismissed

2024-06-20 07:43 UTC, ioayoub requested changes

2024-06-20 07:43 UTC, ioayoub commented on client/src/components/navbar/NavBar.jsx
> +          {/* Une fois l'utilisateur authentifié, changer "login/signup" par "my account" */}
👀

2024-06-20 07:43 UTC, ioayoub commented on client/src/components/navbar/NavBar.jsx
> +      {/* <h1>
👀

2024-06-20 07:43 UTC, ioayoub commented on client/src/components/navbar/NavBar.jsx
> +        <Link to="/">Origins Digital</Link>
👀

2024-06-20 08:00 UTC, ioayoub approved these changes

2024-06-20 08:03 UTC, JohaneDecamps approved these changes

2024-06-20 08:04 UTC, MichaelLELU approved these changes

2024-06-20 08:05 UTC, camille-haxa approved these changes

2024-06-20 08:05 UTC, merged