S05 us00 style login signup
WildCodeSchool-2024-02/WildCodeSchool-2024-02-JS-Remote-JavaScrypte-P3-DigiCode pull request #80
Opened 2024-07-14 14:41 UTC by JohaneDecamps

2024-07-14 19:22 UTC, aurelienLavanchy commented on client/src/main.jsx
> +        path: "/hystory9",
you mispelled `history`

2024-07-15 07:48 UTC, JohaneDecamps commented on client/src/main.jsx
> +        path: "/hystory9",
✅

2024-07-15 08:10 UTC, MichaelLELU submitted a review, later dismissed

2024-07-15 08:11 UTC, aurelienLavanchy submitted a review, later dismissed

2024-07-15 08:17 UTC, ioayoub requested changes

2024-07-15 08:17 UTC, ioayoub commented on client/src/pages/loginpage/LoginPage.jsx
>            {
?

2024-07-15 08:17 UTC, ioayoub requested changes

2024-07-15 08:17 UTC, ioayoub commented on client/src/pages/loginpage/LoginPage.jsx
> +                "application/x-www-form-urlencoded; charset=UTF-8",
?

2024-07-15 08:22 UTC, aurelienLavanchy approved these changes

2024-07-15 08:27 UTC, MichaelLELU approved these changes

2024-07-15 08:38 UTC, aurelienLavanchy approved these changes

2024-07-15 08:50 UTC, MichaelLELU submitted a review, later dismissed

2024-07-15 09:10 UTC, aurelienLavanchy approved these changes

2024-07-15 09:24 UTC, MichaelLELU approved these changes

2024-07-15 09:25 UTC, ioayoub approved these changes

2024-07-15 09:30 UTC, merged